### ISSUE TITLE
Copy link functionality breaks on an1.51-60

### ISSUE THREAD

**Issue by ishaanv** [bkhpanigha/hh-suttas#113]
Since there is a dash in the citation (an1.51-60) it breaks the copy link logic (and perhaps the scroll to hash logic). Need to look at it more closely but one solution could be split on the '-' between a \d and \w.

E.g. In
https://suttas.hillsidehermitage.org/?q=an1.51-60#an1.51-60:1.3-an1.51-60:1.4
an1.51-60 vs 3-a

**Comment by Reptilioo** [comment]
After looking into it for a bit, it seems like the issue comes from the fact that the html segments of suttas composed with a "-" wasn't generated properly so we end up with segments looking like this "an1.51:1.1" instead of like this "an1.51-60:1.1"

**Comment by Reptilioo** [comment]
Also the comment linking an1.51-60 are broken, for example there is one in sn22.81's comment.
We're going to need to check these after the issue is fixed

**Comment by Reptilioo** [comment]
Ok we're good, issue fixed
