### ISSUE TITLE
Improve layout of bookmarks page

### ISSUE THREAD

**Issue by uruvelakassapa** [bkhpanigha/hh-suttas#140]
Two points I can currently see that could be vastly improved

1. spacing of bookmark options. Currently they are too bunched up together. Also would be nice to have labels toggling be less disorientating.
<img width="224" alt="image" src="https://github.com/user-attachments/assets/f1cfdded-4a0e-4c7f-b720-e5c754f0b938">

2. On the mobile view I hypothesise that the bookmarked text would read better if it the entire horizontal width rather than at the moment where it takes up 3/5 of the width.
<img width="456" alt="image" src="https://github.com/user-attachments/assets/0e5475c0-a1d7-4301-a3f2-c9ff5fa909a7">

**Comment by Reptilioo** [comment]
Maybe we could make label toggling to be smooth with an animation instead of abrupt as it is right now to be less disorientating
