### ISSUE TITLE
Hide pali for screen readers

### ISSUE THREAD

**Issue by uruvelakassapa** [bkhpanigha/hh-suttas#142]
It would be nice to be able to send Suttas to kindle (and other reader views). But at the moment the scraped document from the kindle extension looks like this. I believe it's a matter of user 'aria-hidden' attribute appropriately but I could be wrong.
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/e63dcbff-f790-4216-a32a-6a7239b0edee">

**Comment by Reptilioo** [comment]
Is the kindle scrapping extension accessible to non kindle owners? 
If it is only scrapping the HTML I guess any HTML to Mobi/Epub extension app would give kind of the same result to do tests though

Other solutions for you in particular:
- doesn't kindle have a way to browse the web in the way a Pocketbook e-reader does?
- would convert the webpage into a pdf file with a third party web app like this webpage to pdf tool work for you https://webtopdf.com/ ?

**Comment by uruvelakassapa** [comment]
That's interesting. https://webtopdf.com does indeed scrape as expected. 
<img width="797" alt="image" src="https://github.com/user-attachments/assets/fef29be8-1f5c-4fc5-a24b-5ce4a752fdef">

But yes perhaps the better option here is to create native pdfs/epubs which can be used on any e-reader (with the added option of with or without pali e.g. https://readingfaithfully.org/digha-nikaya-translated-by-bhikkhu-sujato-free-epub-kindle-pdf/)

**Comment by uruvelakassapa** [comment]
closing for now because the #164 fulfils the intended purpose
