### ISSUE TITLE
Sutta paragraphs misarrangement

### ISSUE THREAD

**Issue by bkhpanigha** [bkhpanigha/hh-suttas#153]
Compare these two screenshots:

![image](https://github.com/user-attachments/assets/bc1d7bd8-1880-4289-b278-a7e28de4f216)
![image](https://github.com/user-attachments/assets/2081afe1-6036-4db9-8648-b3600df53a6c)

It seems the paragraphs are getting cut short for some reason.

**Comment by uruvelakassapa** [comment]
This was my mistake. Removed css that I shouldn't have. Fixed in the PR linked
