### ISSUE TITLE
Display matched JSON lines in search result list

### ISSUE THREAD

**Issue by bkhpanigha** [bkhpanigha/hh-suttas#170]
Something like this (when searching English, most importantly):
![image](https://github.com/user-attachments/assets/b73e1b18-fcf0-45ce-8369-1bd8045a1444)

Book selection as shown in the image would not be essential for now. Just the part over the yellow background.

**Comment by Reptilioo** [comment]
- [ ] Modify "/python/generated/suttas-database-data.json" to only contain the text without the reference to the verses so as to not have to improve performance by not having to remove them during the search.
- [ ] Set up a html structure either replacing the current content of the page or being displayed over it, which will receive the matching data. It should be simple enough to not require lots of efforts to fit it on every screen sizes.
- [ ] Display sutta reference and highlight matching element
- [ ] Display a loading bar ?
- [ ] Display maximum 100 words around the matching element ?

**Comment by Reptilioo** [comment]
@bkhpanigha Would you mind if this search existed as a new independent page that could maybe be accessed via an "advanced" button next to the usual search bar?

The reason behind it is that I'm thinking about separating the english content from the pali and giving the option to search for one, the other or both, in an attempt to increase search speed. This might not be an issue right now but the more the data to parse, the longer it will take.
This also gives us the chance to add more search options later on, like filtering by books as DPR does.

**Comment by interested-in-dhamma** [comment]
@Reptilioo Given that comment by @bkhpanigha about data scarcity, it is possible to disable the auto downloading of the suttas data and then let the user enable it themselves (before that, the sutta content search will not work).

Alternatively, a service like Algolia can be used which may be a better long term solution if many more suttas get added. SuttaCentral also uses it. https://www.algolia.com/for-open-source/

**Comment by Reptilioo** [comment]
@interested-in-dhamma In this case having two different search system might be beneficial, the basic one searching through suttas ids, titles and headings using only available_suttas.json data as it used to, and the advanced one I'm currently making using what you set up with indexedDB and Dexie, downloading all the available suttas translations/pali and comments.

I will check what Algolia is.

**Comment by interested-in-dhamma** [comment]
@Reptilioo That sounds OK to me. What I think would be good is to make a toggle for online/offline. When offline, the advanced search will be enabled through downloading the suttas. When online, it is disabled (because it requires downloaded data), when a user hovers it there can be a tooltip saying "only available in offline mode" for example.

For the online, potentially it can be made available through Algolia (the open source free version) but I would keep that as something for later and not think about it now.

**Comment by Reptilioo** [comment]
@bkhpanigha @interested-in-dhamma [This version of the draft](https://github.com/Reptilioo/hh-suttas/tree/advanced-search-draft) is working and usable by accessing the "/advanced-search.html" page. Feel free to try it out and tell me what needs to be changed or added.

There are still a small number of things listed at the top of advanced-search.js and as checkboxes above that I need to do.
Also, right now the pali search automatically removes diacritics from the search term and the suttas' text, and returns passages devoid of diacritics. I eventually need to find a good way to show the diacritics version instead with the searchTerm highlighted.

**Comment by interested-in-dhamma** [comment]
Looks great, nice work 👍 

Some things you may want to address:
1. When searching multiple times the same thing the result is different, for example searching "ok" I get a different list, I would expect the same results
2. The search button could be disabled when nothing is entered in the textbox, also when no language is selected, also when no books are selected. (Results would always be empty)
3. For usability, I am a fan of adding `cursor: pointer` to things like checkboxes, so I would recommend adding it there to be clear it is clickable.

**Comment by Reptilioo** [comment]
> When searching multiple times the same thing the result is different, for example searching "ok" I get a different list, I would expect the same results

Thanks for pointing it out, it should always be the same list but I think I know what the issue is here.

> Also, I would keep the position of the header the same on every page.

Could you clarify what you mean, please?

**Comment by Reptilioo** [comment]
@bkhpanigha @interested-in-dhamma Also, should the search return one result for each time the search term are found in a sutta, or show only one result per sutta?

For example if searching for "training", should we have 3 entries pointing to DN2, each at a different line containing "training", or only one entry to the first line containing "training"?

**Comment by interested-in-dhamma** [comment]
> @interested-in-dhamma :
> 
> Thanks for your feedback, all points are now addressed, except for this one:
> 
> > Also, I would keep the position of the header the same on every page.
> 
> Could you clarify what you mean, please?

See the following screenshots:

![screen1](https://github.com/user-attachments/assets/f0053b56-655f-4a01-82e5-c0db2a2a5f2a)
![screen2](https://github.com/user-attachments/assets/8a2af7c8-5c78-4b3d-8e8b-1451c619ca49)

**Comment by Reptilioo** [comment]
Ok I get it now, well I was thinking that for such a page where we would need as much space as possible for the best readability, that it could be better to stack them like that.

**Comment by interested-in-dhamma** [comment]
It's more like a ui/ux thing, to keep things simple and consistent throughout the pages.

As for the styling itself, I would say the header as is now (on the main pages) can be moved a bit more up. For example the `links-area` class now has a `margin-top: 2rem;`, for me that can be removed. So if that gets updated then your page would benefit from it as well.

But this is just my opinion, you can always check with @bkhpanigha.

**Comment by bkhpanigha** [comment]
> @bkhpanigha @interested-in-dhamma Also, should the search return one result for each time the search term are found in a sutta, or show only one result per sutta?
> 
> For example if searching for "training", should we have 3 entries pointing to DN2, each at a different line containing "training", or only one entry to the first line containing "training"?
> 
> Edit: I could also just do an option for it.

 @Reptilioo I think it's best if each individual result is listed. Since that might get out of hand in certain cases (e.g. searching a very ubiquitous short string like "ca"), it might be good to set an upper limit of results per Sutta (let's say 10).
 
 I think the UI looks great as it is right now.

![image](https://github.com/user-attachments/assets/9a0083f4-471b-4ca0-893f-dd4b166909d9)
.

**Comment by interested-in-dhamma** [comment]
I can take a look at the final PR if you like @Reptilioo
