### ISSUE TITLE
Automatic citation linker

### ISSUE THREAD

**Issue by uruvelakassapa** [bkhpanigha/hh-suttas#171]
A suggestion I received from a user:

Whenever we encounter a citation in the comments, if there isn't already a link attached to it in the markdown, link it to the HH Sutta entry if it exists. If not, link it to SuttaCentral entry.
![image](https://github.com/user-attachments/assets/5cbdb670-ef81-4ac6-9777-e937a09d5c28)

Feedback welcome

**Comment by Reptilioo** [comment]
I started to edit every comments so as to add link to the corresponding sutta page if it existed on suttas.hillsidehermitage.org up until MN26 (see #158) but got caught up in the epub generation.

As for adding SuttaCentral links, there's the issue of giving implicit endorsement to views shared by non HH translators that are not in line with HH teachings.
