### ISSUE TITLE
Tidy up the repository

### ISSUE THREAD

**Issue by Reptilioo** [bkhpanigha/hh-suttas#178]
It's quite secondary but it could be nice to reorganize the repository a bit so we have all files of a certain type (python, html, css, json, ...) in a folder named after the type, instead of having all these files piling up at the root.

Also:
- "index.css" could be called "style.css" now that it is used in multiple pages
- "index.js": functions shared between "index.html", "bookmarks.html", "comments.html", "glossary.html",.. could be regrouped in "utils.js".
- In "bookmarks.html", "comments.html", "glossary.html",.. -> "utils.js" could then be called instead of "index.js".

**Comment by wisecameron** [comment]
I'll make a refactored version of the repository and PR it

**Comment by wisecameron** [comment]
https://github.com/wisecameron/hh-suttas/tree/cameron/structural-refactoring

Here's my fork (uses more of a component-based structure) -- I'm about 30% done with refactoring, will probably have it done within a day or two.  You guys are free to use this structure or not -- it will be easier to work on though.

**Comment by uruvelakassapa** [comment]
@Reptilioo I was thinking the same. Esp points two and three.

If you think it's relevant I would also add abstracting away the navbar buttons (home, bookmarks, comments...) into it's own file.

**Comment by wisecameron** [comment]
@uruvelakassapa I'm nearly done with my refactor, it will make this 1000x easier to work on.  Will PR it tonight for sure.

**Comment by wisecameron** [comment]
https://github.com/bkhpanigha/hh-suttas/pull/182  Fixed

**Comment by interested-in-dhamma** [comment]
@wisecameron Nice work. This can be closed?

**Comment by Reptilioo** [comment]
@bkhpanigha @interested-in-dhamma @wisecameron good job on the js cameron.
I was initially proposing to tidy up every files at the root (html, css, python, json, ...) but if you judge it good enough right now let's mark it as completed

**Comment by wisecameron** [comment]
> @bkhpanigha @interested-in-dhamma @wisecameron good job on the js cameron. I was initially proposing to tidy up the root folder with all these files (html, css, python, json, ...) but if you judge it good enough right now let's mark it as completed

Thank you! I think restructuring the other files in the root folder is totally valid and a good idea.  I didn't do it only because I didn't want to go too overboard with my changes.
