### ISSUE TITLE
Flashing Dark mode

### ISSUE THREAD

**Issue by wisecameron** [bkhpanigha/hh-suttas#181]
When the site is loaded locally or on the live version, you see a flash of the dark mode version without any loaded data.  I'll try to figure that out after I refactor the code structure.

**Comment by uruvelakassapa** [comment]
@wisecameron this has been an issue since the beginning and at the time I couldn't figure out a way around it from the js side.

It happens because you need to set some sort of background colour in the initially before the js can read localStorage and get the dark mode setting

**Comment by wisecameron** [comment]
https://github.com/bkhpanigha/hh-suttas/pull/182 Fixed
