### ISSUE TITLE
Add title of each youtube linked 

### ISSUE THREAD

**Issue by uruvelakassapa** [bkhpanigha/hh-suttas#187]
As someone who may not have access to the internet all the time, but have the Suttas and the HH catalogue downloaded, it would be good to know the title of each talk linked to I can look up the corresponding audio file.

E.g. https://suttas.hillsidehermitage.org/?q=mn2#comment1. Not sure how many links are like this. Maybe I can also do it manually as some point. 

Would be nice to have @bkhpanigha feedback on this

**Comment by Reptilioo** [comment]
From what I've seen, in general he tries to put the title of the talk in the link. 
For this specific example the link text is almost the same as the youtube video, and I'm pretty confident that looking for it in the channel search bar would result in finding this specific video.

But you're right that if there are some links not displaying the title of the video, it could be better to modify them.

**Comment by bkhpanigha** [comment]
@uruvelakassapa It's a good point. But I don't think the best solution would be to simply change all links' text to the video title. Wouldn't it be easy enough to make a popup appear showing the title of the video when you first click on a link?

**Comment by uruvelakassapa** [comment]
@Reptilioo actually you're right. I thought this case above was this other group Sutta discussion (which might be MN19, in the end) which wasn't titled as such. I think this can be closed for now and manually fixed if indeed there are titles missing.
