### ISSUE TITLE
"Copy Link" and "Add Bookmark" buttons no longer displaying for highlighted text

### ISSUE THREAD

**Issue by bkhpanigha** [bkhpanigha/hh-suttas#196]

**Comment by Reptilioo** [comment]
Also links to passages aren't working anymore.
For example: https://suttas.hillsidehermitage.org/?q=mn1#mn1:2.2-mn1:2.3 (which was valid before)

**Comment by interested-in-dhamma** [comment]
> Also links to passages aren't working anymore. For example: https://suttas.hillsidehermitage.org/?q=mn1#mn1:2.2-mn1:2.3 (which was valid before)

This also affects the return option from a comment to the text. (It is also a link.)

**Comment by Reptilioo** [comment]
@interested-in-dhamma It is probably a missing reference or missing import to function scrollToHash() in former './js/utils.js' somewhere.

**Comment by bkhpanigha** [comment]
@Reptilioo The buttons themselves now appear and successfully copy the selected link to the clipboard, but if you paste said link into a new tab you get a "not a valid citation" error.
