### ISSUE TITLE
Add a Development environment for testing new features and preventing regressions going to Live

### ISSUE THREAD

**Issue by interested-in-dhamma** [bkhpanigha/hh-suttas#198]
See issue #196 which has some regressions, it would be good to have these in a Development environment so that it does not make it to Live and affect actual users.

Then the development environment can be tested manually and if everything is good it can be pushed to Live.

**Comment by interested-in-dhamma** [comment]
@bkhpanigha After some digging, it seems like the best way is that you make a fork of this repo that can then be deployed through github pages again, because it is not possible to deploy multiple branches of the same repo in github. See https://github.com/orgs/community/discussions/21582

The best workflow I see is to use the fork repo as production, and this repo as development, so that whenever this repo is ok to deploy to production, you only have to sync the fork repo, and then have that be deployed to production after sync.
But I don't know how easy it will be for you to change the fork repo to point to https://suttas.hillsidehermitage.org/

It is also possible to keep this as the production and the fork as development, but then everyone would have to move their work to over there.

It is also an option to keep like it is now and then the PRs just need to be tested more thoroughly if they work as expected.

**Comment by bkhpanigha** [comment]
@interested-in-dhamma I'm not sure I understand how adding that extra step would make a difference. Isn't `main `already the development repo, and `gh-pages` the production one?

**Comment by interested-in-dhamma** [comment]
@bkhpanigha What you are referring to are the branches of the `hh-suttas` repo, and the issue is that github pages does not allow to deploy two separate branches in the same repo, that is why a new repo would be necessary.

So then there would be a development repo --> which deploys to the development environment, which will initially look the same as the suttas.hillsidehermitage website, just that new features will be deployed to here before they will be available there.
And then the production repo --> which deploys to the production environment, this is what the end users will use. So new features will not be immediately in there before tested in the development environment (usually by developers).

**Comment by interested-in-dhamma** [comment]
@bkhpanigha Alternatively, automated tests can be added that would tests all the core functionality and important things that are not being caught now, then it would show if this fails when merging a PR. But it takes more time initially to set all that up and define proper cases, etc.
I saw there are some tests already but they would not run for me locally.

**Comment by interested-in-dhamma** [comment]
@bkhpanigha Nice. Is it possible to point this repo to `https://bkhpanigha.github.io`? Then the problem shouldn't be there.

The linking to the suttas can be fixed in js, but it's not possible to do it for the comments in the json files that link to another sutta.  But it makes sense to keep both environments the same structure.

**Comment by bkhpanigha** [comment]
> @bkhpanigha Nice. Is it possible to point this repo to `https://bkhpanigha.github.io`? Then the problem shouldn't be there.

That seems not possible. Now the repo is deployed here: https://tangerine-selkie-b10e51.netlify.app/. Everything seems to work fine.

**Comment by interested-in-dhamma** [comment]
@bkhpanigha I would be careful with using Netlify because they don't allow you to set limits (unless they changed this recently?), meaning that when there is a lot of traffic that goes over the free tier, they will then try to bill you for it. There was a case like that sometime ago where someone was charged 100k on free tier without credit card linked because of (unplanned) extreme traffic. So personally I wouldn't use them.

I read a bit about CloudFlare pages which looks very interesting, but I was wondering if there is a catch that I didn't see yet because they offer a lot for free (at the bottom): https://pages.cloudflare.com/

**Comment by interested-in-dhamma** [comment]
@bkhpanigha I have been thinking about this some more, considering the scope of the project. To really get benefit out of using a development environment like this we would have to introduce versions, and then have users test it in development, etc. I think it is overkill for this project. It seems now that I also made the workflow more tedious for you which was not my intention. (Basically, what I had in mind is to have a couple of tickets which would then go to development, and then make a "version" out of it (without necessarily calling it a version in the beginning), and THEN push it to live (which would then be done like once a week lets say))

So I would advise to revert this to how it was so that it stays simple for you, which I think is the most important because you may keep using this for a long time, and instead go for the tests approach which now looks like a much better fit. (They would then show whenever there is a PR if all functionality still works with those incoming changes). I am willing to investigate this as well and make a test plan for it (which kind, what tests, technology, etc.), and then implement it if I have time.

(Unless of course you like the current workflow, then by all means keep using it. A thing that may be simplified in that case is to only use 1 repo, because to my knowledge you can use netlify to host a specific branch, so that can be pointed to "development" branch of this repo for example.)

Please let me know what you prefer.

**Comment by interested-in-dhamma** [comment]
Looks like the workflow has some benefits as it is now, so I will close this issue. More tests can always be added later in a new issue.

**Comment by bkhpanigha** [comment]
@interested-in-dhamma Yes, that's what I was planning to say. Technically I think it's possible to deploy two branches of the same repo individually (although only one of them can use GH pages), but one benefit I see with this current setup is being able to test new functionality in workflow files (buildTestDeploy.yml) before pushing it to the live repo. It also makes it much easier to test on mobile, and just makes the whole testing affair a lot more realistic, I find. It also hasn't been too much work to manage the two separate repos so far.

As for programmed tests, I agree that we should still do that sometime in the future.
