### ISSUE TITLE
Suttas are not shown locally on latest branch

### ISSUE THREAD

**Issue by interested-in-dhamma** [bkhpanigha/hh-suttas#199]
See picture. Does anyone else have this?

![suttas-not-shown-locally](https://github.com/user-attachments/assets/45dc18ec-6ae0-4e9e-87ac-8aa63db223c8)

**Comment by Reptilioo** [comment]
Yes, the if(window.location.href == "https://suttas.hillsidehermitage.org/" || window.location.href.startsWith("https://suttas.hillsidehermitage.org/?q=")){ cause issue on local servers though. Not sure if you use that added in #192 caused this, not sure what is the best way to handle this, only add another condition for localhost maybe?

**Comment by bkhpanigha** [comment]
> See picture. Does anyone else have this?

I do. I was about to point it out.

**Comment by Reptilioo** [comment]
@bkhpanigha give me 20 mins and I will PR a fix

**Comment by bkhpanigha** [comment]
> @bkhpanigha give me 20 mins and I will PR a fix

@Reptilioo Sure, no rush.
