### ISSUE TITLE
Option: add a Project board for better overview

### ISSUE THREAD

**Issue by interested-in-dhamma** [bkhpanigha/hh-suttas#201]
Here issues can be prioritized, and also can be used to easier see what is being worked on.

Example columns:

"No status" --> Has new issues that are not planned yet, or issues that may be done later.
"Todo" --> Has the issues that need to be done next, with the highest priority listed first.
"In Progress" --> Has the issues that are being worked on.
"In Review" --> Has the issues that are in review. In case of a comment in the review that needs to be addressed before merging, it goes back to "In Progress". In case it is Approved, it goes to "Merged".
"Merged" --> Has the issues that are merged and ready to be tested.
"Accepted" --> Has the issues that are tested and accepted (no bugs).

**Comment by interested-in-dhamma** [comment]
@bkhpanigha Is it also possible to give rights to assign people to issues? It will make it even clearer who works on what when viewing the board.

**Comment by bkhpanigha** [comment]
> @bkhpanigha Is it also possible to give rights to assign people to issues? It will make it even clearer who works on what when viewing the board.
@interested-in-dhamma I thought I did that already?

**Comment by Reptilioo** [comment]
@bkhpanigha We can't assign people in the "Assignees" field (top right) of an issue.

**Comment by interested-in-dhamma** [comment]
> > @bkhpanigha Is it also possible to give rights to assign people to issues? It will make it even clearer who works on what when viewing the board.
> 
> @interested-in-dhamma I thought I did that already?

I have access now.
