### ISSUE TITLE
All Sutta Nipata Links Broken

### ISSUE THREAD

**Issue by bkhpanigha** [bkhpanigha/hh-suttas#207]
![image](https://github.com/user-attachments/assets/13a7ca0c-36ce-4120-904a-c24b4431646a)

**Comment by Reptilioo** [comment]
@bkhpanigha I think I just fixed it. I didn't mean to directly do the modification on this branch, that is something I will have to keep in mind with the new "Collaborator" status.

**Comment by interested-in-dhamma** [comment]
> @bkhpanigha I think I just fixed it. I didn't mean to directly do the modification on this branch, that is something I will have to keep in mind with the new "Collaborator" status.

@bkhpanigha I think it is possible to set the main branch as protected so that one cannot directly push to it (except the owner and admins). That is probably a good thing to add, to help avoiding accidental pushing there by collaborators.
