### ISSUE TITLE
Previous/Next sutta buttons

### ISSUE THREAD

**Issue by interested-in-dhamma** [bkhpanigha/hh-suttas#209]
1. Should display Previous button when there is a previous sutta available
2. Should display Next button when there is a next sutta available
3. Add sutta citation and name in the button

**Comment by Reptilioo** [comment]
It was probably intended at some point because we already have the #navigation div with the "previous" and "next" buttons at the bottom of the sutta pages.

Having the sutta title would be a nice detail I presume.

**Comment by interested-in-dhamma** [comment]
@bkhpanigha The functionality is working now, I am looking at the styling now if you have any requests. Any preference for certain color?
Also I could add left/right arrow icons?

![Image](https://github.com/user-attachments/assets/6dd88cf8-e53f-4553-a020-d60f9e687f6a)

**Comment by interested-in-dhamma** [comment]
![Image](https://github.com/user-attachments/assets/433543a2-3cf9-460d-8ee2-9e0b6a3b952e)

**Comment by Reptilioo** [comment]
I like the "--dark-brown: #3F3234;" (not yet in index.css) or "--dark-orange: #8B4000;", maybe it could be nice on light mode with white/grey characters?

I think right/left arrows and text-align is better indeed.

**Comment by bkhpanigha** [comment]
@interested-in-dhamma Looks nice. For the "bubble" think the same color as the foreword and heading text in the home page would work well. As for the text, whatever has the greatest contrast.
