### ISSUE TITLE
Improve formatting for highlights?

### ISSUE THREAD

**Issue by ghost** [bkhpanigha/hh-suttas#29]
Currently we are highlighting like below. I was wondering if it would be preferable to have something more temporary that showcases the highlight and then fades away. E.g a distinct box, highlighting or peculiar formatting that then fades back into normal text.
<img width="813" alt="image" src="https://github.com/bkhpanigha/hh-suttas/assets/4453276/08d71574-b847-4b7d-82f0-999a87296fb3">

**Comment by Reptilioo** [comment]
@uruvelakassapa @bkhpanigha I find that the highlighting is a bit too much, when you send a link to a big chunk of text, opening the page is really aggressive to the eye and I find it doesn't look really good, am I the only one?

Maybe we could make the highlighting more subtle by removing the bolding and font-size change (or make it less big but still bigger than the rest of the text) and just keeping the shadows around the highlighted text?

I believe a mix of something "temporary that showcases the highlight and then fades away" as it is proposed in this Issue, and then a subtle sign that the text is highlighted like a slightly different color than the rest would be enough and more pleasing to look at.

**Comment by Reptilioo** [comment]
I tested to highlight the text in a flashy color first and then to fade away in black, but that doesn't really add much since the text still ends up highlighted after it.
And I'm not sure we should remove the highlighting entirely because it is always nice to know the boundaries of the passage that was shared.
