### ISSUE TITLE
Notifications dialog box

### ISSUE THREAD

**Issue by ishaanv** [bkhpanigha/hh-suttas#30]
More of a nice to have but we have some messages that we want to display to the user to notify of successful operations. They probably best live in a disappearing dialog box that pops up towards the top of the screen. Current examples of notifications:  
<img width="588" alt="image" src="https://github.com/bkhpanigha/hh-suttas/assets/4453276/72bef9f8-c87c-4e15-9c10-7ae988c86de0">
<img width="444" alt="image" src="https://github.com/bkhpanigha/hh-suttas/assets/4453276/267b58e8-8673-4450-9881-e1d7bfa31823">

**Comment by bkhpanigha** [comment]
Good point, it'd be better to have the download notifications show up the same as the clipboard ones.
