### ISSUE TITLE
Correct link not copied for highlighting if Pali not selected

### ISSUE THREAD

**Issue by bkhpanigha** [bkhpanigha/hh-suttas#32]
![image](https://github.com/bkhpanigha/hh-suttas/assets/53958588/1381b736-c5b3-45b6-8546-d483c5d865b0)
@ishaanv

**Comment by ishaanv** [comment]
There seems to be another bug where the parent of the selected id is highlighted (thus all the children are highlighted). e.g.

https://suttas.hillsidehermitage.org/?q=mn10#mn10:3.2

<img width="442" alt="image" src="https://github.com/bkhpanigha/hh-suttas/assets/4453276/d6226202-c84e-47cc-9d86-d85f0eebd7e8">
