### ISSUE TITLE
Licence for translations and repo?

### ISSUE THREAD

**Issue by ghost** [bkhpanigha/hh-suttas#36]
@bkhpanigha in the readme here perhaps we can have explict licences that govern the software and the translations? 

You can decide on the translations given a list here: https://creativecommons.org/share-your-work/cclicenses/. 

For the software itself I can suggest either the MIT or Unlicense. Open to other suggestions: https://choosealicense.com/licenses/.

**Comment by bkhpanigha** [comment]
For the software I'd go with Unilicense, and for the translations the "CC BY-NC-SA".
