### ISSUE TITLE
Sutta cards on main page

### ISSUE THREAD

**Issue by ishaanv** [bkhpanigha/hh-suttas#69]
@bkhpanigha would you like to organise the main page to something similar to this?
i.e. add Pali title, author information, heading/tag, and optionally a shorter summary or description of the sutta/
![image](https://github.com/bkhpanigha/hh-suttas/assets/4453276/40dc86fd-fab0-4a30-bea3-6b091f97cd96)

**Comment by bkhpanigha** [comment]
I would rather keep it as it is with just the headings. It'll get quite cluttered to have even such short descriptions, even with the amount of Suttas we already have that could deserve it.
