### ISSUE TITLE
Reorganise available_suttas.json

### ISSUE THREAD

**Issue by ishaanv** [bkhpanigha/hh-suttas#77]
Since we have a few nikayas now, we should restructure this file so that structure can be leveraged in different parts of the code.

**Comment by Reptilioo** [comment]
Hi, what do you mean exactly by restructuring that structure so it can be leveraged in different parts of the code?

**Comment by ishaanv** [comment]
@Reptilioo 
Currently available_suttas.json looks like:
```
{
    "available_suttas": [
        {
            "id": "DN2",
            "title": "The Fruits of the Ascetic Life ",
            "pali_title": "Samannaphalasutta"
        },...
}
```
I'm thinking it could be something like:
```
{
    "available_suttas": {
        "DN": {
            "DN2": {
                "id": "DN2",
                "title": "The Fruits of the Ascetic Life",
                "pali_title": "Samannaphalasutta",
                "path": "suttas/translation_en/dn/dn2_translation-en-anigha.json"
            }
            ...
        }
  ```
  
This would simply the following bits

https://github.com/bkhpanigha/hh-suttas/blob/80ed0cd254222a9b96af3274c68edfcfd1504f76/index.js#L18-L37
https://github.com/bkhpanigha/hh-suttas/blob/80ed0cd254222a9b96af3274c68edfcfd1504f76/index.js#L57-L62
https://github.com/bkhpanigha/hh-suttas/blob/80ed0cd254222a9b96af3274c68edfcfd1504f76/index.js#L80-L95
https://github.com/bkhpanigha/hh-suttas/blob/80ed0cd254222a9b96af3274c68edfcfd1504f76/index.js#L373-L397

Plus I need to find an easy way to get the file path given a sutta citation for the bookmarks feature. So I'll probably start working on something to fix this issue. Any thoughts or concerns welcome in the meantime.

**Comment by Reptilioo** [comment]
Sure that's doable, it is just going to be modifying quite a few things in the code as you already showed with these bits, same for the search function

**Comment by ishaanv** [comment]
@Reptilioo Agree it's a big undertaking but the effort will only accumulate from here. Will check out the search and download sections, thanks for the heads up.
