### ISSUE TITLE
Download notification box issue

### ISSUE THREAD

**Issue by Reptilioo** [bkhpanigha/hh-suttas#98]
There is an issue with `infoButton.addEventListener("click", function (event)){});` and `document.addEventListener("click", function (event) {});` being called in `displaySuttas()` -> everytime a search is made, a new similar event is added to `infoButton` (at least on chrome) so if this button have an even number of the same event: when clicking the button the box is shown and directly hidden.
-> We could just put these `addEventListener()` to the end of `index.js`

Another thing, is `.info-notification-box` supposed to show in the upper-center side of the viewport?

**Comment by bkhpanigha** [comment]
@Reptilioo 

> Another thing, is .info-notification-box supposed to show in the upper-center side of the viewport?

Yes, ideally. No particular preference though.

I've moved the `addEventListener()`s to the very end and the issue with search seems to be fixed.
